# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glyphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emojiglyph',
            name='character',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
