# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memecore', '0001_initial'),
        ('glyphs', '0002_auto_20160308_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojiglyph',
            name='tags',
            field=models.ManyToManyField(related_name='emoji_glyphs', to='memecore.Tag'),
        ),
    ]
